export {
  performUnifiedSearch,
  highlightMatches,
  getUniqueSources,
  getAllUniqueTags,
  getQuickDateRanges,
  extractSource,
  DEFAULT_FILTERS,
  type SearchableContentType,
  type DateRange,
  type SearchFilters,
  type HighlightedText,
  type SearchResultBase,
  type ConversationSearchResult,
  type JournalSearchResult,
  type InsightSearchResult,
  type UnifiedSearchResult,
  type SearchSummary,
  type UnifiedSearchResponse,
} from './unified-search';
